export { HomePage } from './Home/HomePage'
export { ProductList } from './Products/ProductList'
export { ProductDetail } from './ProductDetail'
export { Login } from './Login'
export { Register } from './Register'
export { CartPage } from './Cart/CartPage'
export { OrderPage } from './Order/OrderPage'
export { DashBoardPage } from './DashBoard/components/DashBoardPage'